---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ecmsp-project/manifests-kubernetes.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDeaDwLl2Fev5XcOBeGuYoswJFc8YgE/bNnA2U072C5VAAAAJhBTj6xQU4+
    sQAAAAtzc2gtZWQyNTUxOQAAACDeaDwLl2Fev5XcOBeGuYoswJFc8YgE/bNnA2U072C5VA
    AAAEAzaXbvdMnnVrHkEutPI0sW881eazTaJosW9PZhiUM/sd5oPAuXYV6/ldw4F4a5iizA
    kVzxiAT9s2cDZTTvYLlUAAAAE2V4YW1wbGVAZXhhbXBsZS5jb20BAg==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
